ALTER TABLE risks
ADD COLUMN probability REAL NOT NULL DEFAULT 0.0,
ADD COLUMN impact REAL NOT NULL DEFAULT 0.0;

ALTER TABLE risks
ALTER COLUMN probability DROP DEFAULT,
ALTER COLUMN impact DROP DEFAULT;