CREATE TABLE emails (
	id TEXT PRIMARY KEY,
	email_address_to TEXT NOT NULL,
	subject TEXT NOT NULL,
	text_body TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	sent_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX ON emails (sent_at) WHERE sent_at IS NULL;
