ALTER TABLE assets ALTER COLUMN asset_type DROP DEFAULT;
ALTER TABLE assets ALTER COLUMN criticity DROP DEFAULT;
ALTER TABLE assets ALTER COLUMN criticity SET NOT NULL;
ALTER TABLE documents ALTER COLUMN document_type DROP DEFAULT;
ALTER TABLE users_organizations ALTER COLUMN created_at DROP DEFAULT;
