CREATE TYPE control_importance AS ENUM ('MANDATORY', 'PREFERRED', 'ADVANCED');

ALTER TABLE controls ADD COLUMN importance control_importance NOT NULL DEFAULT 'MANDATORY';
ALTER TABLE controls ALTER COLUMN importance DROP DEFAULT;

ALTER TABLE tasks ADD COLUMN time_estimate INTERVAL NOT NULL DEFAULT '00:30:00';
ALTER TABLE tasks ALTER COLUMN time_estimate DROP DEFAULT;

